prompt_parts: # Parts to include, in order. Correspond to files in prompt/parts
  - Title
  - Greeting
  - Introduction
  - Summary
  - Experience
  - Motivation

prompt_params: # Parameters to use in the letter. Correspond to {{ parameter }} in prompt/parts
  style: Very Casual  # Formal, Casual etc.
  focus_skills: Hard Skills  # Hard Skills or Soft Skills etc.
  focus_job_parts: Responsibilities  # Requirements, Responsibilities, Keywords etc.
  num_words: 300  # Number of words in the letter (approximate)

model_params:
  model: gpt-4
  max_tokens: 700
  top_p: 0.95
